In [136]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import pickle
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error

In [137]:
dataname = "wine_quality_red"
missing_type = "quantile"
missing_name = "Q1_complete"
seed = 1
nfold = 5

In [138]:
dataset_path = f"datasets/{dataname}/data.csv"
processed_data_path = (
            f"datasets/{dataname}/{missing_type}-{missing_name}_seed-{seed}.pk"
        )
processed_data_path_norm = (
            f"datasets/{dataname}/{missing_type}-{missing_name}_seed-{seed}_max-min_norm.pk"
        )

In [139]:
processed_data_path_norm

'datasets/wine_quality_red/quantile-Q1_complete_seed-1_max-min_norm.pk'

In [140]:
with open(processed_data_path_norm, "rb") as f:
        observed_values, observed_masks, gt_masks, eval_length = pickle.load(
                    f
                )

In [141]:
observed_values = observed_values
values_nan = observed_values.copy()

In [142]:
values_nan[gt_masks == 0] = np.nan

In [143]:
indlist = np.arange(observed_values.shape[0])

np.random.seed(seed + 1)
np.random.shuffle(indlist)

In [144]:
tmp_ratio = 1 / nfold
start = (int)((nfold - 1) * observed_values.shape[0] * tmp_ratio)
end = (int)(nfold * observed_values.shape[0] * tmp_ratio)

In [145]:
test_index = indlist[start:end]
remain_index = np.delete(indlist, np.arange(start, end))

np.random.shuffle(remain_index)

    # Modify here to change train,valid ratio
num_train = (int)(len(remain_index) * 1)
train_index = remain_index[:num_train]
valid_index = remain_index[num_train:]

In [157]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(values_nan[train_index,:])

SimpleImputer()

In [146]:
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(values_nan[train_index,:])
train_imp = imp.transform(values_nan[train_index,:])
test_imp = imp.transform(values_nan[test_index,:])
#observed_values[train_index,:] - Xrec) ** 2 * (1 - S)) / np.sum(1 - S))))

In [147]:
S_train = np.array(~np.isnan(values_nan[train_index,:]), dtype=float)
S_test = np.array(~np.isnan(values_nan[test_index,:]), dtype=float)

0.1140657909551031

In [158]:
train_imp

array([[0.4852071 , 0.66860465, 0.67806401, ..., 0.88023945, 0.57086328,
        0.74842767],
       [0.5739645 , 0.65891474, 0.62      , ..., 0.86227535, 0.53333334,
        0.74407209],
       [0.6627219 , 0.62082197, 0.745     , ..., 0.87432435, 0.53666667,
        0.71698113],
       ...,
       [0.59199776, 0.62596899, 0.67806401, ..., 0.9141716 , 0.57086328,
        0.68553458],
       [0.6627219 , 0.55813955, 0.70999998, ..., 0.87432435, 0.59666665,
        0.76100633],
       [0.5147929 , 0.71124031, 0.67806401, ..., 0.85828343, 0.57086328,
        0.74407209]])

In [159]:
test_imp

array([[0.56213019, 0.54263564, 0.69999999, ..., 0.85429132, 0.51999998,
        0.81761008],
       [0.50887577, 0.62790697, 0.65999997, ..., 0.87025937, 0.57086328,
        0.74407209],
       [0.56804737, 0.66860465, 0.62      , ..., 0.86227535, 0.69000006,
        0.74407209],
       ...,
       [0.5739645 , 0.65503877, 0.65499997, ..., 0.89421154, 0.58      ,
        0.79245287],
       [0.59199776, 0.62082197, 0.745     , ..., 0.87624753, 0.58999999,
        0.77987421],
       [0.4852071 , 0.62082197, 0.685     , ..., 0.90219556, 0.59999998,
        0.84276729]])

In [4]:
import numpy as np

In [11]:
data = [np.array([[1,2,3,4],[4,5,6,7]]),np.array([[2,2,3,4],[4,5,6,7]]),np.array([[3,2,3,4],[4,5,6,7]])]

In [12]:
data[0].shape

(2, 4)

In [13]:
np.array(data).shape

(3, 2, 4)

In [14]:
np.array(data)

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[2, 2, 3, 4],
        [4, 5, 6, 7]],

       [[3, 2, 3, 4],
        [4, 5, 6, 7]]])